'use client'
import { useCallback, useEffect, useRef, useState } from 'react'
type Draft={id:string;task:string;status:string;instructions:string;updatedAt:string;output:{title:string;content:string;citations:{sourceId:string;quote:string}[];limitations:string[];escalations:string[]}|null;sourceSnapshot:unknown;model:string|null;providerRef:string|null;inputTokens:number|null;outputTokens:number|null;costUsd:string|null;error:string|null;reviewNotes:string|null;photoHash:string|null;photoConsent:string|null;photoDeletedAt:string|null}
type Knowledge={id:string;title:string;content:string;version:number;approvedAt:string|null;isActive:boolean}
type State={pets:{id:string;name:string;breed:{name:string}}[];drafts:Draft[];knowledge:Knowledge[];tasks:string[];configured:boolean;visionConfigured:boolean;canManage:boolean;daily:{requests:number;reportedCostUsd:number;unreported:number;limits:{requests:number;cost:number}}}
const names:Record<string,string>={INTAKE_SUMMARY:'Pet history and intake',GROOMING_PLAN:'Grooming and coat-care plan',VISIT_SUMMARY:'Grooming visit summary',PHOTO_OBSERVATIONS:'Cosmetic photo observations',REBOOKING_MESSAGE:'Rebooking message',TRANSLATION:'Translation',REVIEW_RESPONSE:'Review response',CAMPAIGN_DRAFT:'Campaign draft',STOCK_REVIEW:'Stock replenishment review',STAFF_KNOWLEDGE:'Staff knowledge question'}
const field='w-full rounded border border-gray-300 p-2';const button='rounded bg-primary-700 px-4 py-2 text-white disabled:opacity-50'
export default function Assistant(){
 const retry=useRef<{fingerprint:string;key:string}|null>(null)
 const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const [task,setTask]=useState('INTAKE_SUMMARY'),[petId,setPet]=useState(''),[knowledgeIds,setKnowledge]=useState<string[]>([]),[instructions,setInstructions]=useState(''),[sharing,setSharing]=useState(false),[notes,setNotes]=useState('')
 const [photo,setPhoto]=useState<{data:string;type:string}|null>(null),[consent,setConsent]=useState(''),[entry,setEntry]=useState<Knowledge|null>(null),[title,setTitle]=useState(''),[content,setContent]=useState('')
 const load=useCallback(async()=>{const r=await fetch('/api/assistant',{cache:'no-store'}),v=await r.json();if(!r.ok)throw Error(v.error||'Could not load AI workspace');setData(v)},[])
 useEffect(()=>{load().catch(e=>setError(e.message))},[load])
 async function action(path:string,method:string,input:unknown){const fingerprint=JSON.stringify([path,method,input]);if(retry.current?.fingerprint!==fingerprint)retry.current={fingerprint,key:crypto.randomUUID()};setBusy(true);setError('');setMessage('');try{const r=await fetch(path,{method,headers:{'Content-Type':'application/json','Idempotency-Key':retry.current.key},body:JSON.stringify(input)}),v=await r.json();if(r.status<500)retry.current=null;if(!r.ok)throw Error(v.error||'Request failed');await load();setMessage('Saved. Review the current status and evidence below.');return true}catch(e){setError(e instanceof Error?e.message:'Request failed');return false}finally{setBusy(false)}}
 async function upload(file:File|undefined){setPhoto(null);if(!file)return;if(!['image/png','image/jpeg'].includes(file.type)||file.size>600000){setError('Choose a PNG or JPEG no larger than 600 KB');return}const buffer=await file.arrayBuffer();let binary='';new Uint8Array(buffer).forEach(b=>binary+=String.fromCharCode(b));setPhoto({type:file.type,data:btoa(binary)})}
 async function decide(d:Draft,decision:string){if(!window.confirm(decision==='APPROVE'?'Approve this draft after checking its evidence? This saves your review; it does not send a message or change a booking.':decision==='DELETE_PHOTO'?'Permanently delete this retained photo? Its hash and consent audit remain.':decision==='CANCEL'?'Cancel local processing? The provider may still process or bill the request.':'Reject this draft?'))return;await action('/api/assistant','PATCH',{id:d.id,action:decision,expectedUpdatedAt:d.updatedAt,notes,reviewConfirmed:true})}
 if(!data)return <div className="p-6"><h1 className="text-2xl font-bold">AI drafts & knowledge</h1><p role="alert">{error||'Loading workspace…'}</p><button className={button} onClick={()=>load().catch(e=>setError(e.message))}>Retry</button></div>
 return <main className="mx-auto max-w-5xl space-y-6 p-6">
  <h1 className="text-3xl font-bold">AI drafts & knowledge</h1>
  <p>Prepare grooming notes and customer wording from selected records and approved guidance. Check every draft before use. Medical or safety concerns require qualified staff or veterinary review.</p>
  {error&&<p role="alert" className="rounded bg-red-50 p-3 text-red-800">{error}</p>}{message&&<p role="status" className="rounded bg-green-50 p-3">{message}</p>}
  <p>Today (UTC): {data.daily.requests}/{data.daily.limits.requests} requests · reported cost ${data.daily.reportedCostUsd.toFixed(4)} / ${data.daily.limits.cost} · {data.daily.unreported} requests without reported cost. These limits do not guarantee the provider’s final bill.</p>
  <button className={button} disabled={busy} onClick={()=>load().catch(e=>setError(e.message))}>Refresh workspace</button>
  <form className="space-y-4 rounded border bg-white p-5" onSubmit={async e=>{e.preventDefault();await action('/api/assistant','POST',{task,petId:petId||undefined,knowledgeIds,instructions,sharingConfirmed:sharing,photo:task==='PHOTO_OBSERVATIONS'&&photo?{...photo,consent}:undefined})}}>
   <h2 className="text-xl font-semibold">Create a draft</h2>
   <label className="block">Task<select className={field} value={task} onChange={e=>setTask(e.target.value)}>{data.tasks.map(t=><option key={t} value={t}>{names[t]}</option>)}</select></label>
   <label className="block">Pet record<select className={field} value={petId} onChange={e=>setPet(e.target.value)}><option value="">No pet selected</option>{data.pets.map(p=><option key={p.id} value={p.id}>{p.name} · {p.breed.name}</option>)}</select></label>
   <fieldset className="rounded border p-3"><legend>Approved business guidance</legend>{data.knowledge.filter(k=>k.isActive&&k.approvedAt).map(k=><label key={k.id} className="block"><input type="checkbox" checked={knowledgeIds.includes(k.id)} onChange={e=>setKnowledge(ids=>e.target.checked?[...ids,k.id]:ids.filter(id=>id!==k.id))}/> {k.title} · version {k.version}</label>)}{!data.knowledge.some(k=>k.isActive&&k.approvedAt)&&<p>No approved guidance yet. A manager creates it and a different manager approves it.</p>}</fieldset>
   <label className="block">Instructions or text to translate<textarea className={field} rows={4} minLength={5} maxLength={5000} required value={instructions} onChange={e=>setInstructions(e.target.value)}/></label>
   <p className="text-sm">Evidence includes the selected pet profile and five latest grooming visits; selected guidance; active services for plans/messages/campaigns; current stock for replenishment review. Client contact details and veterinary records are excluded. Avoid personal data in your instructions.</p>
   {task==='PHOTO_OBSERVATIONS'&&<div className="space-y-3"><label className="block">Photo (PNG/JPEG, maximum 600 KB)<input className={field} type="file" accept="image/png,image/jpeg" onChange={e=>upload(e.target.files?.[0])}/></label><label className="block">Owner’s consent reference and scope<input className={field} required minLength={10} maxLength={500} value={consent} onChange={e=>setConsent(e.target.value)}/></label><p className="text-sm">Confirm permission to store this photo privately and share it with the configured vision provider. Include when and how consent was obtained. A manager can delete the retained image after review; the audit and hash remain.</p>{!data.visionConfigured&&<p>A vision model must be configured for photo observations.</p>}</div>}
   <label className="block"><input type="checkbox" required checked={sharing} onChange={e=>setSharing(e.target.checked)}/> I have permission to share these selected records, instructions and any photo with the configured AI provider.</label>
   {!data.configured&&<p>Configure the AI provider and text model to generate drafts.</p>}
   <button className={button} disabled={busy||!sharing||!data.configured||(task==='PHOTO_OBSERVATIONS'&&(!photo||!data.visionConfigured))}>Generate saved draft</button>
  </form>
  <section className="space-y-4"><h2 className="text-xl font-semibold">Saved drafts and review</h2><label className="block">Review notes (required for a decision)<textarea className={field} minLength={5} maxLength={2000} value={notes} onChange={e=>setNotes(e.target.value)}/></label>
   {data.drafts.length===0&&<p>No drafts have been created.</p>}
   {data.drafts.map(d=><article key={d.id} className="space-y-3 rounded border bg-white p-5"><h3 className="text-lg font-semibold">{d.output?.title||names[d.task]} · {d.status}</h3><p className="text-sm">{d.model||'Model pending'} · tokens {d.inputTokens??'unknown'} / {d.outputTokens??'unknown'} · reported cost {d.costUsd===null?'unknown':'$'+d.costUsd}</p>{d.error&&<p role="alert">{d.error}</p>}
    {d.photoHash&&<div><p>Photo consent: {d.photoConsent}</p>{d.photoDeletedAt?<p>Retained photo deleted.</p>:<a className="underline" href={'/api/assistant/photo?id='+encodeURIComponent(d.id)} target="_blank" rel="noreferrer">Open private source photo</a>}</div>}
    {d.output&&<><p className="whitespace-pre-wrap">{d.output.content}</p><ul className="list-disc pl-6">{[...d.output.limitations,...d.output.escalations].map((s,i)=><li key={i}>{s}</li>)}</ul><details><summary>Exact source quotations</summary>{d.output.citations.map((c,i)=><blockquote key={i} className="my-2 border-l-4 pl-3"><strong>{c.sourceId}</strong><p className="whitespace-pre-wrap">{c.quote}</p></blockquote>)}</details></>}
    <details><summary>Evidence snapshot and provider receipt</summary><pre className="overflow-auto whitespace-pre-wrap break-all text-xs">{JSON.stringify({instructions:d.instructions,providerRef:d.providerRef,sources:d.sourceSnapshot},null,2)}</pre></details>
    {d.reviewNotes&&<p>Review: {d.reviewNotes}</p>}
    <div className="flex flex-wrap gap-2">{(d.status==='DRAFT'?['APPROVE','REJECT']:['PENDING','RUNNING','UNKNOWN'].includes(d.status)?['CANCEL']:[]).map(a=><button key={a} className={button} disabled={busy||notes.trim().length<5} onClick={()=>decide(d,a)}>{a==='APPROVE'?'Approve draft':a==='REJECT'?'Reject draft':'Cancel request'}</button>)}{data.canManage&&d.photoHash&&!d.photoDeletedAt&&!['PENDING','RUNNING'].includes(d.status)&&<button className={button} disabled={busy||notes.trim().length<5} onClick={()=>decide(d,'DELETE_PHOTO')}>Delete retained photo</button>}</div>
   </article>)}
  </section>
  {data.canManage&&<section className="space-y-4 rounded border bg-white p-5"><h2 className="text-xl font-semibold">Business guidance</h2><p>Edits revoke approval. A different active manager must review each saved version. Earlier text remains in the audit history.</p><select className={field} aria-label="Guidance to edit" value={entry?.id||''} onChange={e=>{const k=data.knowledge.find(k=>k.id===e.target.value)||null;setEntry(k);setTitle(k?.title||'');setContent(k?.content||'')}}><option value="">Create guidance</option>{data.knowledge.map(k=><option value={k.id} key={k.id}>{k.title} · {k.isActive?(k.approvedAt?'approved':'needs review'):'archived'} · v{k.version}</option>)}</select><label className="block">Guidance title<input className={field} value={title} maxLength={200} onChange={e=>setTitle(e.target.value)}/></label><label className="block">Guidance text<textarea rows={6} className={field} value={content} maxLength={20000} onChange={e=>setContent(e.target.value)}/></label><div className="flex flex-wrap gap-2">{['SAVE',...(entry?['APPROVE','ARCHIVE']:[])].map(a=><button key={a} className={button} disabled={busy||title.trim().length<3||content.trim().length<10} onClick={async()=>{if(a==='APPROVE'&&!window.confirm('Have you reviewed the saved guidance and confirmed it is suitable for staff use?'))return;if(await action('/api/assistant/knowledge','POST',{id:entry?.id,action:a,expectedVersion:entry?.version||0,title,content})){setEntry(null);setTitle('');setContent('')}}}>{a==='SAVE'?'Save guidance':a==='APPROVE'?'Approve saved guidance':'Archive guidance'}</button>)}</div></section>}
  <p className="text-sm">Approval records a staff decision. Messages, bookings, purchases and clinical decisions require their own authorized workflow. Canceling cannot guarantee that a provider stops processing or billing an in-flight request. Unknown requests are never regenerated automatically.</p>
 </main>
}
