'use client'
import { useEffect,useState } from 'react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useMutationFetch } from '@/hooks/use-mutation-fetch'
import Link from 'next/link'
export default function SetupPage(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 const [technician,setTechnician]=useState({userId:'',serviceIds:[] as string[],postalPrefixes:'',baseLatitude:'',baseLongitude:'',maxTravelKm:'',startsAt:'',endsAt:''})
 const [time,setTime]=useState({technicianId:'',startsAt:'',endsAt:'',available:false,reason:''})
 const [stock,setStock]=useState({serviceId:'',productId:'',quantity:1})
 const mutate=useMutationFetch()
 async function load(){try{const r=await fetch('/api/workflow/admin/config');const d=await r.json();if(!r.ok)throw Error(d.error||d.message);setData(d)}catch(e){setError(String(e))}}
 useEffect(()=>{void load()},[])
 async function save(input:object,method='POST'){setBusy(true);setError('');setMessage('');try{const r=await mutate('/api/workflow/admin/config',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});const d=await r.json();if(!r.ok)throw Error(d.message||d.error);setMessage('Configuration saved');await load()}catch(e){setError(String(e))}finally{setBusy(false)}}
 const choice=(label:string,value:string,options:any[],onChange:(id:string)=>void)=><label className="block">{label}<select required className="block border rounded p-2 w-full" value={value} onChange={e=>onChange(e.target.value)}><option value="">Select…</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
 return <div className="max-w-5xl space-y-6"><h1 className="text-3xl font-bold">Groomer setup and availability</h1><p>Configure <Link href="/settings" className="underline">business hours and tax settings</Link> first. Administrators configure profiles; managers can maintain availability.</p>{error&&<p role="alert" className="text-red-700">{error}</p>}{message&&<p role="status">{message}</p>}
 {!data?<Button onClick={load}>Load setup</Button>:<>
 <form className="border rounded p-5 grid md:grid-cols-2 gap-4" onSubmit={e=>{e.preventDefault();void save({...technician,action:'UPSERT_TECHNICIAN',postalPrefixes:technician.postalPrefixes.split(',').map(s=>s.trim()).filter(Boolean),baseLatitude:Number(technician.baseLatitude),baseLongitude:Number(technician.baseLongitude),maxTravelKm:Number(technician.maxTravelKm),startsAt:new Date(technician.startsAt).toISOString(),endsAt:new Date(technician.endsAt).toISOString()})}}>
 <h2 className="text-xl font-semibold md:col-span-2">Groomer profile</h2>{choice('Groomer',technician.userId,data.groomers,id=>{const p=data.profiles.find((p:any)=>p.userId===id);setTechnician({...technician,userId:id,serviceIds:p?.skills.map((s:any)=>s.serviceId)??[],postalPrefixes:p?.serviceAreas.map((a:any)=>a.postalPrefix).join(', ')??'',baseLatitude:String(p?.baseLatitude??''),baseLongitude:String(p?.baseLongitude??''),maxTravelKm:String(p?.maxTravelKm??'')})})}
 <fieldset><legend>Qualified services</legend>{data.services.map((s:any)=><label key={s.id} className="block"><input type="checkbox" checked={technician.serviceIds.includes(s.id)} onChange={e=>setTechnician({...technician,serviceIds:e.target.checked?[...technician.serviceIds,s.id]:technician.serviceIds.filter(id=>id!==s.id)})}/> {s.name}</label>)}</fieldset>
 {([['postalPrefixes','Mobile service postal prefixes (comma separated)','text'],['baseLatitude','Base latitude','number'],['baseLongitude','Base longitude','number'],['maxTravelKm','Maximum travel distance (km)','number'],['startsAt','Available from (your local timezone)','datetime-local'],['endsAt','Available until (your local timezone)','datetime-local']] as const).map(([key,label,type])=><label key={key}>{label}<Input required type={type} step="any" value={technician[key]} onChange={e=>setTechnician({...technician,[key]:e.target.value})}/></label>)}<Button disabled={busy}>Save profile and availability</Button></form>
 <form className="border rounded p-5 grid md:grid-cols-2 gap-4" onSubmit={e=>{e.preventDefault();void save({...time,startsAt:new Date(time.startsAt).toISOString(),endsAt:new Date(time.endsAt).toISOString()},'PATCH')}}><h2 className="text-xl font-semibold md:col-span-2">Availability or time off</h2>{choice('Groomer',time.technicianId,data.groomers,id=>setTime({...time,technicianId:id}))}<label><input type="checkbox" checked={time.available} onChange={e=>setTime({...time,available:e.target.checked})}/> Available for bookings (unchecked blocks time)</label>{(['startsAt','endsAt'] as const).map(key=><label key={key}>{key==='startsAt'?'From':'Until'} (your local timezone)<Input required type="datetime-local" value={time[key]} onChange={e=>setTime({...time,[key]:e.target.value})}/></label>)}<label>Reason<Input required minLength={5} value={time.reason} onChange={e=>setTime({...time,reason:e.target.value})}/></label><Button disabled={busy}>Record availability</Button></form>
 <form className="border rounded p-5 grid md:grid-cols-3 gap-4" onSubmit={e=>{e.preventDefault();void save({...stock,action:'SET_SERVICE_INVENTORY'})}}><h2 className="text-xl font-semibold md:col-span-3">Mobile service inventory consumption</h2>{choice('Service',stock.serviceId,data.services,id=>setStock({...stock,serviceId:id}))}{choice('Product',stock.productId,data.products,id=>setStock({...stock,productId:id}))}<label>Units per service<Input type="number" min="1" required value={stock.quantity} onChange={e=>setStock({...stock,quantity:Number(e.target.value)})}/></label><Button disabled={busy}>Save requirement</Button></form>
 <section className="border rounded p-5 space-y-2"><h2 className="text-xl font-semibold">Provider readiness</h2>{!data.connectors.length?<p>No provider connectors are configured. Mobile quotes require mapping and tax connectors; bookings require calendar and messaging connectors.</p>:data.connectors.map((c:any)=><p key={c.id}>{c.kind} · {c.provider} · {c.enabled?'Enabled':'Disabled'} · credential {c.credentialConfigured?'present':'missing'} · webhook secret {c.webhookConfigured?'present':'not configured'}</p>)}<p className="text-sm">Credential presence does not verify an adapter or a successful provider operation.</p></section>
 <section className="border rounded p-5 space-y-2"><h2 className="text-xl font-semibold">Upcoming availability</h2>{data.availability.map((a:any)=><p key={a.id}>{data.groomers.find((g:any)=>g.id===a.technicianId)?.name} · {new Date(a.startsAt).toLocaleString()} – {new Date(a.endsAt).toLocaleString()} · {a.available?'Available':'Blocked'} · {a.source}</p>)}</section>
 </>}</div>
}
